services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: payments
      # No auth for now
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  # Node.js Express application
  api:
    build:
      context: ./js
      dockerfile: Dockerfile
    container_name: block52-api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NODE_URL=https://node1.block52.xyz
      - PORT=3000
    expose:
      - "3000"
    networks:
      - block52-network

  # Nginx reverse proxy
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: block52-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    depends_on:
      - api
    networks:
      - block52-network

networks:
  block52-network:
    driver: bridge