version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"  # Enable web UI
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - web

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.localhost`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    driver: bridge