
# Docker Compose file (docker-compose.yml)
version: '3.9'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: pvm
      # No auth for now
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017

  pvm:
    build:
      context: ./ts
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongo

  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   ports:
  #     - "443:443"
  #   depends_on:
  #     - pvm
