
# Docker Compose file (docker-compose.yml)
version: '3.9'

services:
  express-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - express-app


